//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: NProtocol.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_NProtocol_H__
#define __WDR_NProtocol_H__

#ifdef __GNUG__
    #pragma interface "NProtocol_wdr.cpp"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define ID_TEXT 10000
#define ID_USERNAME 10001
#define ID_PASSWORD 10002
#define ID_TOCSERVER 10003
#define ID_TOCPORT 10004
#define ID_LOGINSERVER 10005
#define ID_LOGINPORT 10006
wxSizer *AIM( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *Yahoo( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_UIN 10007
#define ID_ICQSERVER 10008
#define ID_ICQPORT 10009
wxSizer *ICQ( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_KITSERVER 10010
#define ID_KITPORT 10011
#define ID_FILESHARING 10012
#define ID_TEXTCTRL 10013
#define ID_BROWSE 10014
wxSizer *KiT( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_LISTBOX 10015
#define ID_BUTTON 10016
#define ID_CHECKBOX 10017
wxSizer *Direct( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *MSN( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
