//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: wxgui.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_wxgui_H__
#define __WDR_wxgui_H__

#ifdef __GNUG__
    #pragma interface "wxgui_wdr.cpp"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions


#define ID_CHAT_NOTEBOOK 10006
wxSizer *ChatWindow( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_SPLITTER 10007
wxSizer *ChatPage1( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_CHAT_HTMLINPUT 10008
#define ID_CHAT_NNIM_BUTTON 10009
wxSizer *ChatPage1b( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_TEXT 10010
#define ID_TEXTCTRL 10011
#define ID_BUTTON 10012
#define ID_CHECKBOX 10013
#define ID_GAUGE 10014
wxSizer *ChatPage2( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );


#define ID_TREE_CONTROL 1000
#define ID_CONTACTS_BUTT_BITMAP 10018
wxSizer *Contacts( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_CON_EDIT_NAME 10019
#define ID_CON_EDIT_INFO_LIST 10020
#define ID_CON_EDIT_ADDINFO 10021
#define ID_CON_EDIT_REMOVEINFO 10022
#define ID_CON_EDIT_INFO_TEXT 10023
#define ID_CON_EDIT_NETS_USER 10024
#define ID_CON_EDIT_ADDNET 10025
#define ID_CON_EDIT_REMOVENET 10026
#define ID_CON_EDIT_NETS_ALL 10027
#define ID_CON_EDIT_NETS_SCREEN_NAME 10028
#define ID_CON_EDIT_NET_PREF 10029
wxSizer *ContactEditor( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );



wxSizer *PrefGeneral( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );



#define ID_PREF_BUTT_ADDCONTACT 10032
wxSizer *PrefContact( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *PrefSecurity( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *PrefPlugins( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *NewUserWizard1( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *NewUserWizard2( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_LISTBOX 10034
wxSizer *NewUserWizard3( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_LOG_LIST 10035
wxSizer *LogView( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_LOADING_GAUGE 10066
wxSizer *Loading( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_VIEW_INFO_HTML 10067
#define ID_VIEW_INFO_OK_BUTTON 10068
wxSizer *ViewInfo( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_AWAY_LIST_CTRL 10069
#define ID_AWAY_AWAY_MSGS 10070
#define ID_AWAY_DISABLE_SOUND 10071
#define ID_AWAY_HIDE_WINDOWS 10072
#define ID_AWAY_BUTTON_BACK 10073
wxSizer *AwayScreen( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions


// Declare toolbar functions

// Declare bitmap functions

wxBitmap MyBitmapsFunc( size_t index );

#endif

// End of generated file
