//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: NWizards.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_NWizards_H__
#define __WDR_NWizards_H__

#ifdef __GNUG__
    #pragma interface "NWizards_wdr.cpp"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define ID_TEXT 10000
#define ID_U_NAME 10001
#define ID_U_PASS1 10002
#define ID_U_PASS2 10003
wxSizer *uWiz1( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_LINE 10004
#define ID_U_ALLNETS 10005
#define ID_U_ADDNET 10006
#define ID_U_CONFNETS 10007
#define ID_U_REMNET 10008
wxSizer *uWiz2( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_C_NAME 10009
#define ID_C_WIZ_EDIT 10010
wxSizer *cWiz1( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_C_ALLNET 10011
#define ID_C_ADDNET 10012
#define ID_C_CONFNET 10013
#define ID_C_REMNET 10014
wxSizer *cWiz2( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *genPrefs( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *secPrefs( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_VIEW_INFO_HTML 10015
#define ID_VIEW_INFO_CLOSE 10016
wxSizer *ViewAway( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_ADD_AWAY_TITLE 10017
#define ID_TEXTCTRL 10018
#define ID_ADD_AWAY_SAVE 10019
wxSizer *AddAway( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_USER_INFO_TREE 10020
#define ID_USER_INFO_ADD 10021
#define ID_USER_INFO_REM 10022
wxSizer *UserTree( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
